os: linux
language: go

go:
  - "1.13"

serivices:
  - docker

addons:
  apt:
    update: true
    packages:
      - build-essential
      - libssl-dev
      - uuid-dev
      - libgpgme11-dev
      - squashfs-tools
      - libseccomp-dev
      - pkg-config
      - make
      - wget
      - cryptsetup-bin
      - git

before_install:
  - gimme list
  - echo ${GIT_ACCOUNT}

env:
  global:
    - GIT_ACCOUNT=tischlab-travis-ci
    - secure: "n8r/m5tTiq9cWS8O6VrIWgfcQLCDPNRdyvg1sd7U8cToNpQ2V9lwCFkE9a9xXfQEYtVdQbkdGQn6n7NTv9InEMlVYp70HvAghgwfrASPoqHXJoATQDIAY5rZsEZqSP21MFHXLs+KFGPdjNrqj0q+TCI/XvffoYMC8q0QzOKUZ0wv99ca+01B4t3Z5cYtXenhiR/+MdfGMZ3f/X98w3h+fqBwgfbbLgCDNT27jQzyX8rJnutwX8LfWDopcoO/U2Iw7cDCg6zXuDZZz9Fb+YyE9m1QV595wXL/gr/sUNt/POWsBD1i6kDvv3l3gYVa9Gjk7cfIT661f7zOtxSy0zqSgIy6N1PaKaEPWwEmR3LlYkNOSrUTwyqrtpUOZATmb1W/qxuYd7d9p01VxJJFNYXcfQdl3Ad02oWM51gFgGkIcnmanHwvrMcAqeEK66ZyvCJ/+b6s8CWmi5Ceuwg8omaCjN6k0mbTXeDX5J9DUNc8lvuDAhGaHVi5kWyKgMMrwDsgCyVxBKkIO+xTCgdTmztEiexZLv1zA1HZWJK+cN8Xhke+MLKcBrmEjFAyVzmasw3Tlrd93yrY9W/0JIOTIsksKbWyIJ1K+XK0NYl8Vg4b1rEs7YNiLH1uVrurd9uPDkAgz2tWvgXjp4ptKsolxAiZMwTAfKK9Nj6Z7BqpwXJCapY="

script:
  # Install singularity
  - git clone https://github.com/sylabs/singularity.git
  - cd singularity
  - git checkout v3.5.0
  - ./mconfig
  - make -C ./builddir
  - sudo make -C ./builddir install
  - cd ..
  # Bulid docker file
  - mkdir /tmp/image
  - docker build -t moseq2 --build-arg SERVICE_TOKEN=${SERVICE_ACCOUNT_TOKEN} --build-arg GIT_NAME=${GIT_ACCOUNT} .
  # Convert docker image to singularity image https://github.com/singularityhub/docker2singularity/blob/master/README.md
  - docker run -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/image:/output --privileged -t --rm quay.io/singularity/docker2singularity moseq2
  - docker save moseq2 > moseq2-docker.tar
  - ls /tmp/image

before_deploy:
  - export TRAVIS_TAG="v${TRAVIS_BUILD_NUMBER}"
  - echo $TRAVIS_TAG
  - git tag $TRAVIS_TAG
  - export RELEASE_NAME=moseq2.${TRAVIS_TAG}.tar.gz
  - mv /tmp/image .
  - tar -czvf ${RELEASE_NAME} image

deploy:
  provider: releases
  api_key:
    secure: NTNjBhh2Fzc8D9T6rFcq8YD8jzIpojHLglKvYvWCQrgo+J8kWfqtWuqrHWQAUjyM7pgwDCoN2UtwviHxXlNvQU+y/c+1orODXAZqvXPMQRcLBcJqsGmOwuBgUosaBvwmAKPGnB4Vun270u3dnHKKAbYN7JKNrI2L4eUcHVEwmuJKEH/Trf4X/uTp68FKZlEJqb6hMEqTZnJCybtY/XQ7qjS/SitojBog2Ub06PGM8dEVZBa/SBq410TqzfnNkYRUN2tCkhBmoD27kVqEcwVGtnp/66P6xMdXW2AsuIOLskMcEYplnT4V1FmlHTJGiMxJzmvUthUKeGiRUPHYrXJDpfofN3FZNPb3UAnjScxa59yLfIk6pRItXSM7Oda4g6FMfjEKSio8+TMdcMFrNLlyBJc2rrGGikYp02ATJUDPTqtUW7JyTMctqn+nfv+3Hm42ssQupFAmSdDLOoQUGQEvlaKQydgXsmHXDUBcH9tSJl+jCaSHqu8K5A62OkD0Kx6tW2fAb0uPuCM6F8Gm0O6TDzphSjwm4lLBCCJoWDsAC9xH8Kw4ydTcTKOShK8s6VckAwfFXVwgieZvJSLYrsqhqIezTidYvg6RP75hE1P+al2k91dThmr1bCl01Idn4o/dXf0RvlBaddNQ+GaJJdTHE+2QKlU9Ol2f2AS+jv7RXLA=
  skip_cleanup: true
  file_glob: true
  file: "${RELEASE_NAME}"
  tag_name: "${TRAVIS_TAG}"
  on:
    branch: entry-point-automation