angle_hampel_sig: 3
angle_hampel_span: 0
bg_roi_depth_range:
- 650
- 750
bg_roi_dilate:
- 10
- 10
bg_roi_fill_holes: true
bg_roi_gradient_filter: false
bg_roi_gradient_kernel: 7
bg_roi_gradient_threshold: 3000
bg_roi_index: 0
bg_roi_shape: ellipse
bg_roi_weights:
- 1
- 0.1
- 1
cable_filter_iters: 0
cable_filter_shape: rectangle
cable_filter_size:
- 5
- 5
centroid_hampel_sig: 3
centroid_hampel_span: 0
chunk_overlap: 0
chunk_size: 1000
compress: false
compress_chunk_size: 3000
compress_threads: 3
config_file: null
crop_size:
- 80
- 80
flip_classifier: /moseq2_data/flip_files/flip_classifier_k2_c57_10to13weeks.pkl
flip_classifier_smoothing: 51
fps: 30
frame_dtype: uint8
frame_trim:
- 0
- 0
max_height: 100
min_height: 10
model_smoothing_clips:
- 0
- 0
output_dir: null
spatial_filter_size:
- 3
tail_filter_iters: 1
tail_filter_shape: ellipse
tail_filter_size:
- 9
- 9
temporal_filter_size:
- 0
tracking_model_init: raw
tracking_model_ll_clip: -100
tracking_model_ll_threshold: -100
tracking_model_mask_threshold: -16
tracking_model_segment: true
use_plane_bground: false
use_tracking_model: false
write_movie: true
